### ISSUE TITLE
json_decode(): Passing null to parameter #1 ($json) of type string is deprecated

### ISSUE THREAD

**Issue by jamai1** [eversign/eversign-php-sdk#71] opened 2022-09-16 09:10 UTC
eversign-php-sdk/sdk/Eversign/ApiRequest.php line 225 causes a deprecated warning:
```
$requestOptions['json'] = json_decode($this->payLoad);
```

Passing null to non-nullable internal function parameters is deprecated since PHP 8.1

**Comment by milanlatinovic** [comment] 2022-10-25 08:00
Hi @jamai1,

I will close this issue because it is missing context and steps to reproduce.
If you want to continue resolving this, please reopen the issue using proper bug report format, [an example can be found here](https://github.com/eversign/eversign-php-sdk/issues/new?assignees=&labels=&template=bug_report.md&title=).

It is important to describe how you got to this error.
Based on the info you provided, your integration code is sending nullable payload to json_decode function, which looks like an issue with base code, not with sdk.

Kind regards,
Milan

**Closed as completed by milanlatinovic** 2022-10-25 08:00 UTC
Labels: invalid
