### ISSUE TITLE
Composer 2 namespace issue

### ISSUE THREAD

**Issue by olischmidt123** [eversign/eversign-php-sdk#35] opened 2020-12-03 05:04 UTC
Warning of skipping a class when using composer2 autoloading.
Warning:
Class Eversign\OauthTokenRequest located in ./vendor/eversign/eversign-php-sdk/sdk/Eversign/OAuthTokenRequest.php does not comply with psr-0 autoloading standard. Skipping.

Download composer 2.
Install your package.
![Bildschirmfoto 2563-12-03 um 12 04 03](https://user-images.githubusercontent.com/23320154/100966516-a7e68600-355f-11eb-8a4e-e8613ab64196.png)

Since php8 requires composer2, this issue is not trivial when using the package.
Right now the workaround is to install the package with composer2 and do a dumpautoload with composer1 right after.

**Comment by milanlatinovic** [comment] 2020-12-07 10:24
Hi @olischmidt123 I see you closed the original issue?
Can I ask why? You decided to proceed with your workaround or something else?

I am just curios. Thanks!

**Comment by olischmidt123** [comment] 2020-12-07 10:31
Hey,

I just noticed it kinda disappeared.
Didn't see any commit resolving it but for me it seems to work now

**Comment by milanlatinovic** [comment] 2020-12-07 11:15
Ah, it makes sense then.
I tried to reproduce this issue, by installing composer 2.x and to install this package, and for me everything worked.
Yes, there were no commits solving this, it might have been something environmental.

In any case, thanks for reporting, I will keep issue closed, and if someone else have same issues we can revisit it again.

Thanks for contributing!

**Comment by olischmidt123** [comment] 2020-12-08 06:16
Problem still consists.
I just messed up my branches and it wasnt installed in the one i was working on lately.
So:
I'm on a php8 environment. My namespace is set up like this:
`    
    "require": {
        "eversign/eversign-php-sdk": "dev-master"
    },
"autoload": {
        "psr-4": {
            "My\\Api\\": [
                "src/"
            ]
        }
    }`

**Comment by olischmidt123** [comment] 2020-12-08 06:20
My guess:
Your package autoload config is now:
        "psr-0": { "Eversign\\": "sdk/" }
But might should be:
        "psr-0": { "Eversign\\": "sdk/Eversign" }

[https://www.php-fig.org/psr/psr-0/](https://www.php-fig.org/psr/psr-0/)

**Comment by milanlatinovic** [comment] 2020-12-10 11:15
Hi @olischmidt123 , I don't think the issue is autoload config related.

From what is your initial screenshot telling us, there seems to be a issue in class name (capitalization of 'a', 'A' letter is different in the class name and actual file).

I made a fix here 
https://github.com/eversign/eversign-php-sdk/pull/36/commits/e4916b4c844d40f7c5d9db95b9688051efe881e1

Please try it out, release https://github.com/eversign/eversign-php-sdk/releases/tag/1.18.0

**Comment by olischmidt123** [comment] 2020-12-11 07:44
Hey @milanlatinovic 
thanks for the quick fix! autoloading works perfectly fine now, warning is gone.
![eversign](https://user-images.githubusercontent.com/23320154/101876650-570a0980-3bbf-11eb-8a27-10ff8653db9b.png)

**Comment by milanlatinovic** [comment] 2020-12-11 08:59
Fantastic @olischmidt123, thanks for the followup :)

I will close this issue now and announce Composer 2 compatibility and new release on LinkedIn and Twitter, under hashtag #eversign #eversignsdk.

If you notice anything else in future, please let us know, by creating a new issue.

Once again, thanks! :)

**Closed as completed by milanlatinovic** 2020-12-11 08:59 UTC
Labels: wontfix
